### PR TITLE
fix: Deal with concurrent hub access better

### LINKED ISSUE #237: Bug: Using sentry_debug on a non-main thread before init may break Hub::main
Referenced code: [`hub.rs`]

**TL;DR**: Using `sentry_debug` may break `Hub::main` if it happens too early on a non-main thread. Using the `debug-log` feature may avoid this behavior.

[`Hub::main`] reads from a lazy-static [`PROCESS_HUB`] value. When `PROCESS_HUB` is first used, it is initialized with the thread ID of the current thread. It is assumed that the first usage of `PROCESS_HUB` is in the main function (via `sentry::init`), but this is not always the case.

There are also two thread-local values, [`THREAD_HUB`] and [`USE_PROCESS_HUB`]. `USE_PROCESS_HUB` holds a boolean which decides if the current thread should use the main thread's hub, aka `PROCESS_HUB`. These thread-locals are used by [`Hub::with`] to figure out if the hub should be taken from `PROCESS_HUB` or `THREAD_HUB`.

The issue occurs if the first usage of `PROCESS_HUB` is outside of the main thread. This initializes its thread ID to the current thread ID, which is not the main thread's ID. Future calls to `Hub::with` on the main thread will use `THREAD_HUB` instead of `PROCESS_HUB`. Since the Sentry client is initialized on the main thread, and the main thread is not using `PROCESS_HUB`, the initialized client is inaccessible to other threads.

The concrete way that this occurs in my code is when I provide a non-default transport in the client options (Edit: happens with the default reqwest transport as well):
```rust
let curl_transport_factory = |options: &sentry::ClientOptions| {
    Arc::new(sentry::transports::CurlHttpTransport::new(options)) as Arc<dyn sentry::Transport>
};
let options = sentry::ClientOptions {
    transport: Some(Arc::new(curl_transport_factory)),
    release: sentry::release_name!(),
    ..sentry::ClientOptions::default()
};
let client = sentry::init(options);
```

[The transport factory method is called before the client is bound to the hub][create_transport]. [`CurlHttpTransport::new`] spawns a thread which immediately calls [`sentry_debug`]. `sentry_debug` uses `log::debug` when the `debug-logs` feature is enabled (a non-default feature), but otherwise uses `Hub::with`. As long as the new thread reaches the `Hub::with` call before the main thread accesses `PROCESS_HUB`, this bug is triggered.

[`hub.rs`]: https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry-core/src/hub.rs
[`Hub::main`]: https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry-core/src/hub.rs#L132
[`Hub::with`]: https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry-core/src/hub.rs#L141
[`PROCESS_HUB`]: https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry-core/src/hub.rs#L19
[`THREAD_HUB`]: https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry-core/src/hub.rs#L27
[`USE_PROCESS_HUB`]: https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry-core/src/hub.rs#L29
[create_transport]: https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry-core/src/client.rs#L102
[`CurlHttpTransport::new`]: https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry/src/transport.rs#L289
[`sentry_debug`]: https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry-core/src/macros.rs#L56

### PR DESCRIPTION
**Pull request by Swatinem**
This should fix #237, and we should backport this to 0.19 as well.

### CODE REVIEW

File: sentry-log/src/integration.rs [hunk 1]
```diff
@@ -43,8 +43,7 @@ impl Integration for LogIntegration {
         }
 
         INIT.call_once(|| {
-            // silently ignore errors here, as running tests will hit this condition for some reason.
-            log::set_boxed_logger(Box::new(Logger::default())).ok();
+            log::set_boxed_logger(Box::new(Logger::default())).unwrap();
```
Comment (jan-auer) [inline sentry-log/src/integration.rs:46]: Just in case someone already set the logger, should we still `.ok()` here, or even log the error? Even if this is a static programming error, it's a bit harsh to panic here.

File: sentry-core/src/hub.rs [hunk 2]
```diff
@@ -48,12 +48,14 @@ impl HubImpl {
...
     fn is_active_and_usage_safe(&self) -> bool {
-        let guard = match self.stack.try_read() {
-            Err(TryLockError::Poisoned(err)) => err.into_inner(),
-            Err(TryLockError::WouldBlock) => return false,
+        let guard = match self.stack.read() {
+            Err(err) => err.into_inner(),
             Ok(guard) => guard,
         };
-        guard.top().client.is_some()
+        if let Some(client) = guard.top().client.as_ref() {
```
Comment (jan-auer) [inline sentry-core/src/hub.rs:55]: You can shorten this to:

```suggestion
        if let Some(ref client) = guard.top().client {
```

A match:

```suggestion
        match guard.top().client {
            Some(ref client) => client.is_enabled(),
            None => false,
        }
```

Or even a one-liner:

```suggestion
        guard.top().client.as_ref().map_or(false, |c| c.is_enabled())
```

**Review by jan-auer — APPROVED** [review]

**Comment by jan-auer** [comment]
@Swatinem does this also fix https://github.com/getsentry/sentry-rust/issues/239?

File: sentry-log/src/integration.rs (hunk 1 above)
Comment (Swatinem) [reply sentry-log/src/integration.rs:46]: We had the `unwrap` here originally, which I changed just recently: https://github.com/getsentry/sentry-rust/commit/97b90064a464dc0e1a01b081091b5d2e1d4f6941#diff-8c955be4e92f6bf80501c6237c378f5e

After looking into this with @mitsuhiko we think it was rather a problem of libbacktrace segfaulting on us. Since we should rather fail hard in case of misconfiguration rather than silently not do anything, I think its okay to `unwrap` here, in the case the user has really configured the logger twice.

File: sentry-core/src/hub.rs (hunk 2 above)
Comment (Swatinem) [reply sentry-core/src/hub.rs:55]: ahhh, the expressive power of rust ;-)

**Comment by Swatinem** [comment]
> does this also fix #239?

I will do some more tests also on windows where I was also seeing this problem.

File: sentry-log/src/integration.rs (hunk 1 above)
Comment (jan-auer) [reply sentry-log/src/integration.rs:46]: Well, the original `log::set_boxed_logger` also doesn't panic and rather errors. The problem is that it's much harder to recover from a panic than from an  error, and our SDK should never crash user apps, even when misconfigured. I'd rather log an error and disable the integration than make the user application crash. Imagine this is only triggered with production configuration for some customers and then hits them where it hurts them most.
